### ISSUE TITLE
Prueba 02

### ISSUE THREAD

**Issue by rullroice** [lonkonao/classAndroid2024#28]
Hola profesor! Soy Raúl Ibarra, aqui esta mi enlace.
Feliz dieciocho!!
(https://github.com/rullroice/AndroidJava01.git)

**Comment by lonkodev** [comment]
link invalido

**Comment by rullroice** [comment]
https://github.com/rullroice/AndroidJava01.git 

Revise profesor, me deja ingresar en el Git.
