### ISSUE TITLE
Los 7 Fantásticos

### ISSUE THREAD

**Issue by DaddyChary** [lonkonao/classAndroid2024#3]
Link del repositorio: https://github.com/DaddyChary/CalculadoraAndroid

**Comment by DaddyChary** [comment]
Integrantes: Gamaliel Moya, Antonio Verdugo, Matías Baeza, Leonardo Miranda, Luis Tobar, Joaquín Olivares, Erika Aristizábal

**Comment by lonkodev** [comment]
revisado
