### ISSUE TITLE
🏓🏓 Tenimesistas e Informaticos Forever - Benjamín Fuenzalida y Jorge Lecaro

### ISSUE THREAD

**Issue by ProgramadorLX777** [lonkonao/classAndroid2024#6]
https://github.com/ProgramadorLX777/CalculadoraNewVersion

Nota: La calculadora si se requiere empezar una operación desde 0 se debe presionar el botón de "reset". Para confusiones de acumulación de operaciones.

**Comment by lonkodev** [comment]
Revisado
