### ISSUE TITLE
Calculadora

### ISSUE THREAD

**Issue by Hopu-dev** [lonkonao/classAndroid2024#7]
https://github.com/Hopux1/Calculadora_android

Integrantes: André Piffaut, Jesús Vidal, Francisco Zamorano, Oscar Zuñiga.

**Comment by lonkodev** [comment]
El proyecto ha sido modificado de manera que no cumple con lo solicitado, que era agregar y modificar funcionalidades. El proyecto ya tenía un layout definido, y solo se debían quitar los ceros de los decimales y permitir la entrada de varios números. Además, considerando el retraso en la entrega del trabajo, no puedo proceder con la evaluación.
